# Generated by Django 2.1.2 on 2018-10-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='category',
            field=models.CharField(default='life', max_length=100),
            preserve_default=False,
        ),
    ]
